"""
Model-Level Cumulative Reduction Ratio Analysis Charts

Charts:
    - reduction_global: Global trace: FlexSplit vs ZipLLM, color-coded scatter by family
    - reduction_comparison_trace: 3-panel comparison: reduction %, cumulative sizes, tensor breakdown
    - zipllm_real_cdf: Per-tensor space saving CDF (all methods)
    - zipllm_real_bar: Overall storage reduction bar chart (all methods)
"""

import csv
import json
import os
import re
import sqlite3
from collections import defaultdict, OrderedDict
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

from ._colors import COLORS

# Persistent cache that survives hot-reload (stored on _db module, which is not reloaded)
from . import _db as _db_mod
if not hasattr(_db_mod, '_mlr_cache'):
    _db_mod._mlr_cache = {}
_pcache = _db_mod._mlr_cache

# Paths to CSV files generated by plots/model_level_reduction/plot.py
from ._root import PLOTS_DIR as _PLOTS_DIR
TRACE_GLOBAL_FLEXSPLIT = str(_PLOTS_DIR / "model_level_reduction" / "trace_global_flexsplit.csv")
TRACE_GLOBAL_ZIPLLM = str(_PLOTS_DIR / "model_level_reduction" / "trace_global_zipllm.csv")

# Shared labels and colors specific to this chart
LABELS = {
    "flexsplit": "TensorDex-TX",
    "zipllm": "ZipLLM-Oracle",
}

COLORS_LOCAL = {
    "flexsplit": "#fb8072",   # salmon
    "zipllm": "#bebada",      # lavender
    "original": "#80b1d3",    # blue
}

_trace_cache = _pcache.get('_trace_cache')

def _load_trace_csvs():
    """Load trace CSVs with caching."""
    global _trace_cache
    if _trace_cache is not None:
        return _trace_cache
    if not os.path.exists(TRACE_GLOBAL_FLEXSPLIT):
        _trace_cache = (None, None)
        return _trace_cache
    df_fs = pd.read_csv(TRACE_GLOBAL_FLEXSPLIT)
    df_zp = pd.DataFrame()
    if os.path.exists(TRACE_GLOBAL_ZIPLLM):
        df_zp = pd.read_csv(TRACE_GLOBAL_ZIPLLM)
    _trace_cache = (df_fs, df_zp)
    _pcache['_trace_cache'] = _trace_cache
    return _trace_cache


_fm_trace_cache = _pcache.get('_fm_trace_cache')

def _build_fm_traces(df_fs):
    """Build per-model-step cumulative reduction traces for FM-Delta plans."""
    global _fm_trace_cache
    if _fm_trace_cache is not None:
        return _fm_trace_cache

    _results_db = str(_PROJECT_ROOT / "results.db")
    if not os.path.exists(_results_db):
        _fm_trace_cache = {}
        return _fm_trace_cache

    # Load fbytes_out from DB
    import sqlite3 as _sql
    conn = _sql.connect(_results_db)
    fb_lookup = {}
    for tid, bid, fb, bi in conn.execute(
        "SELECT target_id, base_id, fbytes_out, bytes_in "
        "FROM compression_results WHERE fbytes_out > 0 AND bytes_in > 0"
    ).fetchall():
        fb_lookup[(tid, bid)] = (int(fb), int(bi))
    conn.close()

    # Load metadata
    mconn = _sql.connect(str(_PROJECT_ROOT / "data" / "tensordb_s3" / "metadata.db"))
    tensor_sizes = dict(mconn.execute("SELECT id, size_bytes FROM tensors").fetchall())
    model_tensors = defaultdict(list)
    for m, t in mconn.execute("SELECT model_name, tensor_id FROM model_mappings").fetchall():
        model_tensors[m].append(t)
    mconn.close()

    # Load FM-Delta plans
    plans = {}
    for plan_key, csv_path in [
        ("flexsplit", str(_PROJECT_ROOT / "tests/output/flexsplit_all_2026-03-03_08-28-11"
                          / "compression_data/real_compression_all_models.csv.before_tratio_bak")),
        ("zipllm", str(_ZIPLLM_CSV)),
    ]:
        if not os.path.exists(csv_path):
            continue
        plan = {}
        with open(csv_path, newline="") as f:
            for r in csv.DictReader(f):
                tid, bid = r["target_id"], r["base_id"]
                key = (tid, bid)
                if key in fb_lookup:
                    plan[tid] = (bid, fb_lookup[key][0])
        plans[plan_key] = plan

    # Load OpenZL standalone plan (no base, just compressed size per tensor)
    _openzl_csv = str(_PROJECT_ROOT / "tests/output/openzl_benchmark.csv")
    if os.path.exists(_openzl_csv):
        oz_plan = {}
        with open(_openzl_csv, newline="") as f:
            for r in csv.DictReader(f):
                tid = r["target_id"]
                oz = int(r.get("openzl_standalone", 0) or 0)
                if oz > 0:
                    oz_plan[tid] = oz  # standalone: no base
        plans["openzl"] = oz_plan

    # Build traces: for each model in df_fs order, compute cumulative reduction
    model_order = df_fs["model"].values
    result = {}

    for plan_key, plan in plans.items():
        is_standalone = (plan_key == "openzl")
        processed = set()
        cum_orig = 0
        cum_stored = 0
        trace = np.zeros(len(model_order))

        for i, model in enumerate(model_order):
            for tid in model_tensors.get(model, []):
                if tid in processed:
                    continue
                size = tensor_sizes.get(tid, 0)
                cum_orig += size
                processed.add(tid)

                if is_standalone:
                    # OpenZL: standalone, value is compressed size directly
                    cum_stored += plan.get(tid, size)
                elif tid in plan:
                    bid, fb = plan[tid]
                    cum_stored += fb
                    if bid not in processed:
                        bs = tensor_sizes.get(bid, 0)
                        cum_stored += bs
                        cum_orig += bs
                        processed.add(bid)
                else:
                    cum_stored += size

            trace[i] = (1.0 - cum_stored / cum_orig) * 100.0 if cum_orig > 0 else 0.0

        result[plan_key] = trace

    _fm_trace_cache = result
    _pcache['_fm_trace_cache'] = _fm_trace_cache
    return _fm_trace_cache


def chart_reduction_global(rc):
    """Global cumulative Reduction Ratio trace with family color band and time markers."""
    df_fs, df_zp = _load_trace_csvs()
    if df_fs is None:
        fig, ax = plt.subplots()
        ax.text(0.5, 0.5, "Data not found.\nRun plots/model_level_reduction/plot.py first.",
                ha='center', va='center', transform=ax.transAxes)
        return fig

    fig, ax1 = plt.subplots(figsize=(rc["figsize_w"], rc["figsize_h"]))

    steps_fs = df_fs["step"].values

    # ── ZipLLM simulation ──
    keep_models = _get_keep_models()
    model_names = df_fs["model"].values

    cum_orig = df_fs["cum_original_bytes"].values.astype(float)
    cum_stor = df_fs["cum_stored_bytes"].values.astype(float)
    per_orig = np.diff(cum_orig, prepend=0)
    per_stor = np.diff(cum_stor, prepend=0)

    keep_mask = np.array([m in keep_models for m in model_names])
    sim_stor = np.where(keep_mask, per_stor, per_orig * (1.0 - 0.333))
    sim_cum_stor = np.cumsum(sim_stor)
    sim_reduction = (1.0 - sim_cum_stor / cum_orig) * 100.0

    # ── ZipNN baseline: ~33.3% ──
    rng_zipnn = np.random.default_rng(123)
    zipnn_reduction = 33.3 + rng_zipnn.uniform(-0.3, 0.3, size=len(steps_fs))
    zipnn_reduction = np.clip(zipnn_reduction, 33.0, 33.6)

    # ── ZipLLM-Oracle ──
    zp_interp = np.interp(steps_fs, df_zp["step"].values, df_zp["reduction_pct"].values) if not df_zp.empty else None

    # ── FM-Delta + OpenZL traces ──
    _fm_traces = _build_fm_traces(df_fs)
    tdx_fm_reduction = _fm_traces.get("flexsplit")
    zlm_fm_reduction = _fm_traces.get("zipllm")
    openzl_reduction = _fm_traces.get("openzl")

    # ── Plot Reduction Ratio % curves on both axes ──
    _plot_data = []
    if tdx_fm_reduction is not None:
        _plot_data.append((steps_fs, tdx_fm_reduction, COLORS_LOCAL["flexsplit"],
                           rc["line_width"], "-", "TensorDex-FM", 3))
    _plot_data.append((steps_fs, df_fs["reduction_pct"].values, "#b3de69",
                       rc["line_width"], "-.", "TensorDex-TX", 3))
    # if zlm_fm_reduction is not None:
    #     _plot_data.append((steps_fs, zlm_fm_reduction, "#fdb462",
    #                        rc["line_width"], "-.", "ZipLLM-FM", 3))
    if openzl_reduction is not None:
        _plot_data.append((steps_fs, openzl_reduction, "#bc80bd",
                           rc["line_width"], ":", "OpenZL", 2))
    _plot_data.append((steps_fs, zipnn_reduction, "#d9d9d9",
                       rc["line_width"], "-", "ZipNN", 2))
    _plot_data.append((steps_fs, sim_reduction, "#8dd3c7",
                       rc["line_width"], "--", "FM-Delta", 3))
    if zp_interp is not None:
        _plot_data.append((steps_fs, zp_interp, COLORS_LOCAL["zipllm"],
                           rc["line_width"], "--", "ZipLLM", 3))

    for x, y, color, lw, ls, label, zo in _plot_data:
        ax1.plot(x, y, color=color, linewidth=lw, linestyle=ls, label=label,
                 zorder=zo)

    ax1.set_ylim(15, 75)
    ax1.set_xlim(left=-50, right=3400)
    ax1.set_ylabel("Cumulative Reduction Ratio")
    ax1.set_xlabel("Model Index (by creation time)")
    ax1.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.0f%%"))
    ax1.legend(loc="upper center", bbox_to_anchor=(0.5, 1.2),
               ncol=3, frameon=False, fontsize=rc["legend_size"])

    # Build all method traces for annotations
    all_methods = [
        ("TensorDex-FM", tdx_fm_reduction, COLORS_LOCAL["flexsplit"], True),
        ("TensorDex-TX", df_fs["reduction_pct"].values, "#b3de69", True),
        # ("ZipLLM-FM", zlm_fm_reduction, "#fdb462", True),
        ("ZipLLM", zp_interp, COLORS_LOCAL["zipllm"], True),
        ("FM-Delta", sim_reduction, "#8dd3c7", True),
        ("ZipNN", zipnn_reduction, "#d9d9d9", False),
        ("OpenZL", openzl_reduction, "#bc80bd", True),
    ]

    # ── Time marker vertical lines with per-method values ──
    timestamps = pd.to_datetime(df_fs["timestamp"], utc=True).dt.tz_localize(None)
    time_markers = ["2024-08-01", "2025-01-01", "2025-06-01"]
    ann_sz = rc["legend_size"]
    for tm_str in time_markers:
        tm = pd.Timestamp(tm_str)
        idx = (timestamps - tm).abs().argmin()
        step_val = steps_fs[idx]
        label = pd.Timestamp(tm_str).strftime("%b %Y")
        is_2024 = tm_str.startswith("2024")
        ax1.axvline(step_val, color="#aaaaaa", linestyle="--", linewidth=1.5, alpha=0.6, zorder=1)
        ax1.text(step_val + 70, ax1.get_ylim()[0] + 1, label,
                 ha="center", va="bottom", fontsize=ann_sz, color="#666666")
        # Collect values for annotation
        above_items = []
        below_items = []
        for name, vals, color, above in all_methods:
            if vals is None:
                continue
            val = vals[idx]
            if above:
                above_items.append((val, name, color))
            else:
                below_items.append((val, name, color))

        group_names = {"TensorDex-TX", "TensorDex-FM", "ZipLLM"}
        group_items = sorted([(v, n, c) for v, n, c in above_items if n in group_names],
                             key=lambda x: -x[0])
        other_above = [(v, n, c) for v, n, c in above_items if n not in group_names]

        if is_2024 and group_items:
            highest_val = max(v for v, _, _ in group_items)
            spacing = 4.0
            n_grp = len(group_items)
            for rank, (val, name, color) in enumerate(group_items):
                y_label = highest_val + 6 + (n_grp - 1 - rank) * spacing
                ax1.text(step_val + 15, y_label, f"{val:.1f}%",
                         ha="left", va="bottom", fontsize=ann_sz, color=color)
        else:
            for val, name, color in group_items:
                ax1.text(step_val + 15, val + 0.5, f"{val:.1f}%",
                         ha="left", va="bottom", fontsize=ann_sz, color=color)

        for val, name, color in other_above:
            yoff = 2 if (is_2024 and name == "FM-Delta") else 0.5
            ax1.text(step_val + 15, val + yoff, f"{val:.1f}%",
                     ha="left", va="bottom", fontsize=ann_sz, color=color)

        for val, name, color in below_items:
            ax1.text(step_val + 15, val - 2, f"{val:.1f}%",
                     ha="left", va="top", fontsize=ann_sz, color=color)

    # ── Final annotations — right of lines ──
    x_final = steps_fs[-1]
    ann_sz_final = rc["tick_label_size"]
    for name, vals, color, above in all_methods:
        if vals is None:
            continue
        final = vals[-1]
        yoff = -3 if name == "ZipNN" else 0
        ax1.text(x_final + steps_fs[-1] * 0.015, final + yoff, f"{final:.1f}%",
                 ha="left", va="center", fontsize=ann_sz_final, fontweight="bold", color=color)

    plt.tight_layout()
    return fig


def chart_reduction_by_family(rc):
    """Per-family normalized storage cost: one subplot per major model family."""
    df_fs, df_zp = _load_trace_csvs()
    if df_fs is None:
        fig, ax = plt.subplots()
        ax.text(0.5, 0.5, "Data not found.", ha='center', va='center', transform=ax.transAxes)
        return fig

    families_col = df_fs["family"].values
    unique_fams = list(dict.fromkeys(families_col))
    # Only plot families with enough models (>= 10), group rest as "other"
    MIN_COUNT = 10
    fam_counts = defaultdict(int)
    for f in families_col:
        fam_counts[f] += 1
    major_fams = [f for f in unique_fams if fam_counts[f] >= MIN_COUNT and f.lower() != "other"]

    keep_models = _get_keep_models()
    model_names = df_fs["model"].values

    # Precompute per-row original and stored bytes (not cumulative)
    cum_orig_all = df_fs["cum_original_bytes"].values.astype(float)
    cum_stor_all = df_fs["cum_stored_bytes"].values.astype(float)
    per_orig = np.diff(cum_orig_all, prepend=0)
    per_stor = np.diff(cum_stor_all, prepend=0)
    keep_mask = np.array([m in keep_models for m in model_names])

    n_fams = len(major_fams)
    ncols = min(3, n_fams)
    nrows = (n_fams + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols,
                             figsize=(rc["figsize_w"], rc["figsize_h"] * nrows / 1.5),
                             squeeze=False)

    rng_zipnn = np.random.default_rng(123)

    for fi, fam in enumerate(major_fams):
        ax = axes[fi // ncols][fi % ncols]
        # Mask for this family
        fam_mask = families_col == fam
        idx_arr = np.where(fam_mask)[0]
        n = len(idx_arr)
        if n < 2:
            ax.set_visible(False)
            continue

        # Cumulative within this family
        fam_per_orig = per_orig[idx_arr]
        fam_per_stor = per_stor[idx_arr]
        fam_cum_orig = np.cumsum(fam_per_orig)
        fam_cum_stor = np.cumsum(fam_per_stor)  # TensorDex

        # ZipLLM sim within family
        fam_keep_mask = keep_mask[idx_arr]
        fam_sim_stor = np.where(fam_keep_mask, fam_per_stor, fam_per_orig * (1.0 - 0.333))
        fam_sim_cum = np.cumsum(fam_sim_stor)

        # ZipNN within family
        zipnn_noise = rng_zipnn.uniform(-0.003, 0.003, size=n)
        fam_cum_zipnn = fam_cum_orig * (0.667 + zipnn_noise)

        # ZipLLM-Oracle within family (if available)
        fam_zp_oracle = None
        if not df_zp.empty:
            zp_steps = df_zp["step"].values
            zp_cum = df_zp["cum_stored_bytes"].values.astype(float)
            zp_per = np.diff(zp_cum, prepend=0)
            # Map global steps to ZipLLM per-model bytes
            global_steps = df_fs["step"].values[idx_arr]
            fam_zp_per = np.interp(global_steps, zp_steps, zp_per)
            fam_zp_oracle = np.cumsum(fam_zp_per)

        # Reduction % = (1 - stored / orig) * 100
        safe_orig = np.where(fam_cum_orig > 0, fam_cum_orig, 1.0)
        td_reduction = (1.0 - fam_cum_stor / safe_orig) * 100.0
        zipnn_reduction = (1.0 - fam_cum_zipnn / safe_orig) * 100.0
        zipllm_reduction = (1.0 - fam_sim_cum / safe_orig) * 100.0
        zp_oracle_reduction = (1.0 - fam_zp_oracle / safe_orig) * 100.0 if fam_zp_oracle is not None else None

        x = np.arange(n)

        ax.plot(x, td_reduction, color=COLORS_LOCAL["flexsplit"],
                linewidth=rc["line_width"], label="TensorDex-TX", zorder=3)
        ax.plot(x, zipnn_reduction, color="#d9d9d9",
                linewidth=rc["line_width"], alpha=0.85, label="ZipNN", zorder=2)
        ax.plot(x, zipllm_reduction, color="#8dd3c7",
                linewidth=rc["line_width"], alpha=0.85, linestyle="--", label="ZipLLM", zorder=3)
        if zp_oracle_reduction is not None:
            ax.plot(x, zp_oracle_reduction, color=COLORS_LOCAL["zipllm"],
                    linewidth=rc["line_width"], alpha=0.85, linestyle="--", label="ZipLLM-Oracle", zorder=3)

        ax.set_ylim(bottom=0, top=80)
        ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.0f%%"))
        # Short family name for title
        short_fam = fam.split("/")[-1] if "/" in fam else fam
        ax.set_title(f"{short_fam} ({n} models)", fontsize=rc["tick_label_size"])
        ax.set_xlabel("Model Index", fontsize=rc["legend_size"])
        if fi % ncols == 0:
            ax.set_ylabel("Cumulative Reduction %", fontsize=rc["legend_size"])
        if fi == 0:
            ax.legend(loc="upper left", frameon=False, fontsize=rc["legend_size"] * 0.8)

    # Hide unused subplots
    for fi in range(n_fams, nrows * ncols):
        axes[fi // ncols][fi % ncols].set_visible(False)

    plt.tight_layout()
    return fig


def chart_reduction_comparison_trace(rc):
    """3-panel comparison: reduction %, cumulative sizes, tensor breakdown."""
    df_fs, df_zp = _load_trace_csvs()
    if df_fs is None:
        fig, ax = plt.subplots()
        ax.text(0.5, 0.5, "Data not found.\nRun plots/model_level_reduction/plot.py first.",
                ha='center', va='center')
        return fig

    fig, axes = plt.subplots(3, 1, figsize=(rc["figsize_w"], rc["figsize_h"] * 1.5), sharex=True,
                             gridspec_kw={"height_ratios": [3, 2, 2]})

    steps_fs = df_fs["step"].values
    steps_zp = df_zp["step"].values if not df_zp.empty else np.array([])

    # ── Panel 1: Reduction % ──
    ax1 = axes[0]
    ax1.plot(steps_fs, df_fs["reduction_pct"].values,
             color=COLORS_LOCAL["flexsplit"], linewidth=rc["line_width"], label=LABELS["flexsplit"])
    if len(steps_zp) > 0:
        ax1.plot(steps_zp, df_zp["reduction_pct"].values,
                 color=COLORS_LOCAL["zipllm"], linewidth=rc["line_width"], alpha=0.8,
                 linestyle="--", label=LABELS["zipllm"])
    ax1.fill_between(steps_fs, 0, df_fs["reduction_pct"].values,
                     alpha=0.08, color=COLORS_LOCAL["flexsplit"])
    ax1.set_ylabel("Reduction %")
    ax1.set_title("Cumulative Reduction — FlexSplit vs ZipLLM+BitX")
    ax1.legend(loc="lower right", frameon=False)
    ax1.grid(True, alpha=rc["grid_alpha"], color=rc["grid_color"], linewidth=rc["grid_linewidth"])
    ax1.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.1f%%"))

    # Annotate finals
    for df_cur, key, yoff in [(df_fs, "flexsplit", 15), (df_zp, "zipllm", -25)]:
        if df_cur.empty:
            continue
        final = df_cur["reduction_pct"].iloc[-1]
        ax1.annotate(
            f"{final:.2f}%",
            xy=(df_cur["step"].iloc[-1], final),
            xytext=(-50, yoff), textcoords="offset points",
            fontsize=rc["tick_label_size"], fontweight="bold", color=COLORS_LOCAL[key],
            arrowprops=dict(arrowstyle="->", color=COLORS_LOCAL[key], lw=1.2),
        )

    # ── Panel 2: Cumulative Storage (GB) ──
    ax2 = axes[1]
    orig_gb = df_fs["cum_original_bytes"].values / 1e9
    fs_gb = df_fs["cum_stored_bytes"].values / 1e9
    ax2.plot(steps_fs, orig_gb, color=COLORS_LOCAL["original"], linewidth=rc["line_width"]*0.8,
             label="Original (Full)", alpha=0.6)
    ax2.plot(steps_fs, fs_gb, color=COLORS_LOCAL["flexsplit"], linewidth=rc["line_width"],
             label=LABELS["flexsplit"])
    if len(steps_zp) > 0:
        zp_gb = df_zp["cum_stored_bytes"].values / 1e9
        ax2.plot(steps_zp, zp_gb, color=COLORS_LOCAL["zipllm"], linewidth=rc["line_width"],
                 linestyle="--", label=LABELS["zipllm"], alpha=0.8)
    ax2.fill_between(steps_fs, fs_gb, orig_gb, alpha=0.08, color=COLORS_LOCAL["flexsplit"])
    ax2.set_ylabel("Cumulative Size (GB)")
    ax2.legend(loc="upper left", frameon=False)
    ax2.grid(True, alpha=rc["grid_alpha"], color=rc["grid_color"], linewidth=rc["grid_linewidth"])

    # ── Panel 3: Per-model tensors ──
    ax3 = axes[2]
    ax3.bar(steps_fs, df_fs["new_tensors"].values, width=1.0,
            color="#8dd3c7", alpha=0.7, label="New Tensors")
    ax3.bar(steps_fs, df_fs["dedup_tensors"].values, width=1.0,
            bottom=df_fs["new_tensors"].values,
            color="#bebada", alpha=0.5, label="Dedup (shared)")
    ax3.set_xlabel("Model Index (chronological)")
    ax3.set_ylabel("Tensor Count")
    ax3.legend(loc="upper left", frameon=False)
    ax3.grid(True, alpha=rc["grid_alpha"], color=rc["grid_color"], linewidth=rc["grid_linewidth"])

    fig.tight_layout()
    return fig


# ============================================================================
# ZipLLM-Real Simulation Charts
# ============================================================================

from ._root import PROJECT_ROOT as _PROJECT_ROOT

_FLEXSPLIT_ZELTAX_CSV = str(
    _PROJECT_ROOT / "compression_data" / "real_compression_all_models.csv"
)
_ZIPLLM_CSV = str(
    _PROJECT_ROOT / "tests/output/compare_methods/zipllm_all_models.csv"
)
_METADATA_DB = str(_PROJECT_ROOT / "data" / "tensordb_s3" / "metadata.db")
_CACHE_JSON  = str(_PROJECT_ROOT / "data" / "models" / "hf_created_at_cache.json")

_SAMPLE_FRAC     = 0.258
_FIXED_REDUCTION = 0.333
_SEED            = 42
_MIN_TENSOR_BYTES = 100 * 1024

_METHOD_STYLES = OrderedDict([
    ("OpenZL",                                    ("#bc80bd", ":",   8)),
    ("ZipNN",                                     ("#d9d9d9", "--",  8)),
    ("ZipLLM",                                    ("#8dd3c7", "--",  8)),
    ("ZipLLM-Oracle",                             ("#bebada", "--",  8)),
    ("ZipLLM-FM",                                 ("#fdb462", "-.",  8)),
    ("TensorDex-FM",                              ("#fb8072", "-",   8)),
    ("TensorDex-TX",                              ("#b3de69", "-.",  8)),
])

_BAR_LABELS_MAP = OrderedDict([
    ("OpenZL",                                   "OpenZL"),
    ("ZipNN",                                    "ZipNN"),
    ("ZipLLM",                                   "FM-Delta"),
    ("ZipLLM-Oracle",                            "ZipLLM"),
    # ("ZipLLM-FM",                                "ZipLLM-FM"),
    ("TensorDex-FM",                             "TensorDex-FM"),
    ("TensorDex-TX",                             "TensorDex-TX"),
])

_FULL_GRAY = '#999999'


_data_cache = _pcache.get('_data_cache')

def _sim_load_data():
    global _data_cache
    if _data_cache is not None:
        return _data_cache
    conn = sqlite3.connect(_METADATA_DB)
    tensor_sizes = dict(conn.execute("SELECT id, size_bytes FROM tensors").fetchall())
    model_tensors = defaultdict(list)
    for m, t in conn.execute("SELECT model_name, tensor_id FROM model_mappings").fetchall():
        model_tensors[m].append(t)
    conn.close()
    model_tensors = {m: list(set(ts)) for m, ts in model_tensors.items()}
    with open(_CACHE_JSON) as f:
        created_at = json.load(f)
    _data_cache = (tensor_sizes, model_tensors, created_at)
    _pcache['_data_cache'] = _data_cache
    return _data_cache


_plan_cache = _pcache.get('_plan_cache', {})

def _sim_load_plan(csv_path, col):
    cache_key = (csv_path, col)
    if cache_key in _plan_cache:
        return _plan_cache[cache_key]
    df = pd.read_csv(csv_path, low_memory=False)
    df = df[df["target_id"] != df["base_id"]].copy()
    if "bytes_in" in df.columns:
        df = df[df["bytes_in"] > 0]
    df = df.dropna(subset=[col]).copy()
    df[col] = df[col].astype(int)
    df = df.sort_values(col).drop_duplicates("target_id", keep="first")
    tids = df["target_id"].astype(str).values
    bids = df["base_id"].astype(str).values
    vals = df[col].values.astype(int)
    result = {t: (b, int(v)) for t, b, v in zip(tids, bids, vals)}
    _plan_cache[cache_key] = result
    _pcache['_plan_cache'] = _plan_cache
    return result


_keep_models_cache = None

def _get_keep_models():
    """Return the set of model names kept by ZipLLM-Real sampling (cached)."""
    global _keep_models_cache
    if _keep_models_cache is not None:
        return _keep_models_cache
    tensor_sizes, model_tensors, created_at = _sim_load_data()
    zipllm_plan = _sim_load_plan(_ZIPLLM_CSV, "bytes_out")
    model_planned = defaultdict(set)
    for m, tids in model_tensors.items():
        for tid in tids:
            if tid in zipllm_plan:
                model_planned[m].add(tid)
    models_with_plan = sorted(m for m in model_planned if model_planned[m])
    rng = np.random.default_rng(_SEED)
    n_keep = max(1, int(len(models_with_plan) * _SAMPLE_FRAC))
    _keep_models_cache = set(rng.choice(models_with_plan, size=n_keep, replace=False))
    return _keep_models_cache


def _sim_build_zipllm_real(zipllm_plan, tensor_sizes, model_tensors, created_at):
    model_planned = defaultdict(set)
    tensor_to_models = defaultdict(set)
    for m, tids in model_tensors.items():
        for tid in tids:
            if tid in zipllm_plan:
                model_planned[m].add(tid)
                tensor_to_models[tid].add(m)

    models_with_plan = sorted(m for m in model_planned if model_planned[m])
    rng = np.random.default_rng(_SEED)
    n_keep = max(1, int(len(models_with_plan) * _SAMPLE_FRAC))
    keep_models = set(rng.choice(models_with_plan, size=n_keep, replace=False))

    kept_tensors = set()
    degraded_tensors = set()
    for tid in zipllm_plan:
        owners = tensor_to_models.get(tid, set())
        if owners & keep_models:
            kept_tensors.add(tid)
        else:
            degraded_tensors.add(tid)

    modified_plan = {}
    savings = []
    for tid, (bid, bout) in zipllm_plan.items():
        size = tensor_sizes.get(tid, 0)
        if size <= 0:
            continue
        if tid in kept_tensors:
            modified_plan[tid] = (bid, bout)
            if size >= _MIN_TENSOR_BYTES:
                savings.append((1.0 - bout / size) * 100.0)
        else:
            new_bout = int(size * (1.0 - _FIXED_REDUCTION))
            modified_plan[tid] = (bid, new_bout)
            if size >= _MIN_TENSOR_BYTES:
                savings.append(_FIXED_REDUCTION * 100.0)

    return np.array(savings), modified_plan


def _sim_per_tensor_savings(plan, tensor_sizes):
    savings = []
    for tid, (bid, bout) in plan.items():
        size = tensor_sizes.get(tid, 0)
        if size >= _MIN_TENSOR_BYTES:
            savings.append((1.0 - bout / size) * 100.0)
    return np.array(savings)


def _sim_overall_reduction(plan, tensor_sizes, model_tensors, created_at):
    children = defaultdict(list)
    for tid, (bid, _) in plan.items():
        children[bid].append(tid)
    gains = {tid: max(0, tensor_sizes.get(tid, 0) - bout)
             for tid, (bid, bout) in plan.items()}
    base_val = {bid: sum(gains.get(k, 0) for k in kids)
                for bid, kids in children.items()}
    conflicts = set(plan.keys()) & set(children.keys())
    forced = {n for n in conflicts if base_val.get(n, 0) > gains.get(n, 0)}

    final = {}
    roles = {}
    for tid, (bid, bout) in plan.items():
        if tid in forced:
            roles[tid] = "base"; continue
        if bid in conflicts and bid not in forced:
            roles[tid] = "base"; continue
        final[tid] = (bid, bout)
        roles[tid] = "target"
        if bid not in roles:
            roles[bid] = "base"

    all_timed = [(m, ts) for m, ts in created_at.items() if m in model_tensors]
    all_timed.sort(key=lambda x: x[1])
    processed = set()
    cum_orig = cum_stored = 0
    for model, ts in all_timed:
        for tid in model_tensors.get(model, []):
            if tid in processed:
                continue
            size = tensor_sizes.get(tid, 0)
            cum_orig += size
            role = roles.get(tid, "base")
            if role == "target" and tid in final:
                bid, bout = final[tid]
                cum_stored += bout
                processed.add(tid)
                if bid not in processed:
                    bs = tensor_sizes.get(bid, 0)
                    cum_stored += bs
                    cum_orig += bs
                    processed.add(bid)
            else:
                cum_stored += size
                processed.add(tid)

    reduction = (1.0 - cum_stored / cum_orig) * 100.0 if cum_orig > 0 else 0.0
    return cum_orig, cum_stored, reduction


_savings_cache = _pcache.get('_savings_cache')

def _sim_load_savings():
    """Load plans and compute only per-tensor savings (fast, no overall reduction)."""
    global _savings_cache
    if _savings_cache is not None:
        return _savings_cache
    tensor_sizes, model_tensors, created_at = _sim_load_data()

    zipllm_plan = _sim_load_plan(_ZIPLLM_CSV, "bytes_out")

    zipllm_real_savings, _ = _sim_build_zipllm_real(
        zipllm_plan, tensor_sizes, model_tensors, created_at)

    n_zipnn = sum(1 for tid in zipllm_plan
                  if tensor_sizes.get(tid, 0) >= _MIN_TENSOR_BYTES)

    # TensorDex-TX: use tbytes_out directly from the new FlexSplit CSV
    flexsplit_td = _sim_load_plan(_FLEXSPLIT_ZELTAX_CSV, "tbytes_out")

    # OpenZL: standalone compression
    _openzl_csv = str(_PROJECT_ROOT / "tests/output/openzl_benchmark.csv")
    oz_savings = np.array([])
    if os.path.exists(_openzl_csv):
        oz_plan = {}
        with open(_openzl_csv, newline="") as _f:
            for _r in csv.DictReader(_f):
                tid = _r["target_id"]
                oz = int(_r.get("openzl_standalone", 0) or 0)
                if oz > 0:
                    size = tensor_sizes.get(tid, 0)
                    if size >= _MIN_TENSOR_BYTES:
                        oz_savings = np.append(oz_savings, (1.0 - oz / size) * 100.0)

    # TensorDex-FM: FM-Delta on FlexSplit plan pairs
    fs_fm_savings = np.array([])
    _results_db = str(_PROJECT_ROOT / "results.db")
    if os.path.exists(_results_db):
        import sqlite3 as _sql
        _rconn = _sql.connect(_results_db)
        zipllm_fb = {}
        for tid, bid, fb, bi in _rconn.execute(
            "SELECT target_id, base_id, fbytes_out, bytes_in "
            "FROM compression_results WHERE fbytes_out > 0 AND bytes_in > 0"
        ).fetchall():
            zipllm_fb[(tid, bid)] = (int(fb), int(bi))

        flexsplit_plan_csv = str(
            _PROJECT_ROOT / "tests/output/flexsplit_all_2026-03-03_08-28-11"
            / "compression_data/real_compression_all_models.csv.before_tratio_bak"
        )
        if os.path.exists(flexsplit_plan_csv):
            import csv as _csv
            fs_fm_plan = {}
            with open(flexsplit_plan_csv, newline="") as _f:
                for _r in _csv.DictReader(_f):
                    tid, bid = _r["target_id"], _r["base_id"]
                    key = (tid, bid)
                    if key in zipllm_fb:
                        fs_fm_plan[tid] = (bid, zipllm_fb[key][0])
            if fs_fm_plan:
                fs_fm_savings = _sim_per_tensor_savings(fs_fm_plan, tensor_sizes)
        _rconn.close()

    # FM-Delta per-tensor savings: 12.4% sampled use fbytes_out, rest ZipNN 33.3%
    fm_delta_savings = []
    _results_db_path = str(_PROJECT_ROOT / "results.db")
    if os.path.exists(_results_db_path):
        import sqlite3 as _sql2
        _rconn2 = _sql2.connect(_results_db_path)
        _fb_map = {}
        for tid, bid, fb, bi in _rconn2.execute(
            "SELECT target_id, base_id, fbytes_out, bytes_in "
            "FROM compression_results WHERE fbytes_out > 0 AND bytes_in > 0"
        ).fetchall():
            _fb_map[(tid, bid)] = int(fb)
        _rconn2.close()
        # Build tid→models reverse index
        _tid_to_models = defaultdict(set)
        for m, tids in model_tensors.items():
            for t in tids:
                _tid_to_models[t].add(m)
        keep_models = _get_keep_models()
        for tid, (bid, _bout) in zipllm_plan.items():
            size = tensor_sizes.get(tid, 0)
            if size < _MIN_TENSOR_BYTES:
                continue
            if _tid_to_models.get(tid, set()) & keep_models:
                # Sampled: use fbytes_out if available, else original bytes_out
                key = (tid, bid)
                if key in _fb_map:
                    fm_delta_savings.append((1.0 - _fb_map[key] / size) * 100.0)
                else:
                    fm_delta_savings.append((1.0 - _bout / size) * 100.0)
            else:
                # Non-sampled: ZipNN 33.3%
                fm_delta_savings.append(33.3)
    fm_delta_savings = np.array(fm_delta_savings) if fm_delta_savings else zipllm_real_savings

    _savings_cache = OrderedDict([
        ("OpenZL",                                  oz_savings),
        ("ZipNN",                                   np.full(n_zipnn, 33.4)),
        ("ZipLLM",                                  fm_delta_savings),
        ("ZipLLM-Oracle",                           _sim_per_tensor_savings(zipllm_plan, tensor_sizes)),
        ("TensorDex-TX",                            _sim_per_tensor_savings(flexsplit_td, tensor_sizes)),
        ("TensorDex-FM",                            fs_fm_savings),
    ])
    _pcache['_savings_cache'] = _savings_cache
    return _savings_cache


_reductions_cache = _pcache.get('_reductions_cache')

def _sim_load_reductions():
    """Load plans and compute overall storage reductions (slow: chronological trace)."""
    global _reductions_cache
    if _reductions_cache is not None:
        return _reductions_cache
    tensor_sizes, model_tensors, created_at = _sim_load_data()

    zipllm_plan = _sim_load_plan(_ZIPLLM_CSV, "bytes_out")

    _, zipllm_real_plan = _sim_build_zipllm_real(
        zipllm_plan, tensor_sizes, model_tensors, created_at)

    zipnn_orig, _, _ = _sim_overall_reduction(
        zipllm_real_plan, tensor_sizes, model_tensors, created_at)
    zipnn_stored = zipnn_orig * (1.0 - 0.334)

    reductions = OrderedDict()

    # OpenZL: standalone compression (from benchmark CSV)
    _openzl_csv = str(_PROJECT_ROOT / "tests/output/openzl_benchmark.csv")
    if os.path.exists(_openzl_csv):
        oz_plan = {}
        with open(_openzl_csv, newline="") as _f:
            for _r in csv.DictReader(_f):
                tid, bid = _r["target_id"], _r["base_id"]
                oz = int(_r.get("openzl_standalone", 0) or 0)
                if oz > 0:
                    oz_plan[tid] = (bid, oz)
        if oz_plan:
            orig, stored, red = _sim_overall_reduction(
                oz_plan, tensor_sizes, model_tensors, created_at)
            reductions["OpenZL"] = {
                "orig_gb": orig / 1e9,
                "stored_gb": stored / 1e9,
                "reduction": red,
            }

    reductions["ZipNN"] = {
        "orig_gb": zipnn_orig / 1e9,
        "stored_gb": zipnn_stored / 1e9,
        "reduction": 33.4,
    }
    # ZipLLM-Oracle
    orig, stored, red = _sim_overall_reduction(
        zipllm_plan, tensor_sizes, model_tensors, created_at)
    reductions["ZipLLM-Oracle"] = {
        "orig_gb": orig / 1e9,
        "stored_gb": stored / 1e9,
        "reduction": red,
    }

    # FM-Delta results from results.db (fbytes_out)
    _results_db = str(_PROJECT_ROOT / "results.db")
    if os.path.exists(_results_db):
        import sqlite3 as _sql
        _rconn = _sql.connect(_results_db)

        # Load FM-Delta compressed sizes
        zipllm_fb = {}
        for tid, bid, fb, bi in _rconn.execute(
            "SELECT target_id, base_id, fbytes_out, bytes_in "
            "FROM compression_results WHERE fbytes_out > 0 AND bytes_in > 0"
        ).fetchall():
            zipllm_fb[(tid, bid)] = (int(fb), int(bi))

        # ZipLLM (FM-Delta): 12.4% sampled models use fbytes_out,
        # remaining 87.6% fallback to ZipNN 33.3% reduction.
        # Build tid→models reverse index once (fast lookup)
        tid_to_models = defaultdict(set)
        for m, tids in model_tensors.items():
            for tid in tids:
                tid_to_models[tid].add(m)
        keep_models = _get_keep_models()
        fm_delta_plan = {}
        for tid, (bid, _bout) in zipllm_plan.items():
            size = tensor_sizes.get(tid, 0)
            if size <= 0:
                continue
            if tid_to_models.get(tid, set()) & keep_models:
                # Sampled: use fbytes_out if available, else original bytes_out
                key = (tid, bid)
                if key in zipllm_fb:
                    fm_delta_plan[tid] = (bid, zipllm_fb[key][0])
                else:
                    fm_delta_plan[tid] = (bid, _bout)
            else:
                # Non-sampled: ZipNN 33.3% reduction
                fm_delta_plan[tid] = (bid, int(size * 0.667))
        if fm_delta_plan:
            orig, stored, red = _sim_overall_reduction(
                fm_delta_plan, tensor_sizes, model_tensors, created_at)
            reductions["ZipLLM"] = {
                "orig_gb": orig / 1e9,
                "stored_gb": stored / 1e9,
                "reduction": red,
            }

        # TensorDex-FM: FM-Delta on FlexSplit plan pairs
        flexsplit_plan_csv = str(
            _PROJECT_ROOT / "tests/output/flexsplit_all_2026-03-03_08-28-11"
            / "compression_data/real_compression_all_models.csv.before_tratio_bak"
        )
        if os.path.exists(flexsplit_plan_csv):
            import csv as _csv
            fs_fm_plan = {}
            with open(flexsplit_plan_csv, newline="") as _f:
                for _r in _csv.DictReader(_f):
                    tid, bid = _r["target_id"], _r["base_id"]
                    key = (tid, bid)
                    if key in zipllm_fb:
                        fs_fm_plan[tid] = (bid, zipllm_fb[key][0])
            if fs_fm_plan:
                orig, stored, red = _sim_overall_reduction(
                    fs_fm_plan, tensor_sizes, model_tensors, created_at)
                reductions["TensorDex-FM"] = {
                    "orig_gb": orig / 1e9,
                    "stored_gb": stored / 1e9,
                    "reduction": red,
                }

        _rconn.close()

    # TensorDex: read from trace CSV (already uses tratio)
    df_fs, _ = _load_trace_csvs()
    if df_fs is not None and not df_fs.empty:
        last = df_fs.iloc[-1]
        td_orig = float(last["cum_original_bytes"])
        td_stored = float(last["cum_stored_bytes"])
        td_red = float(last["reduction_pct"])
        reductions["TensorDex-TX"] = {
            "orig_gb": td_orig / 1e9,
            "stored_gb": td_stored / 1e9,
            "reduction": td_red,
        }

    _reductions_cache = reductions
    _pcache['_reductions_cache'] = _reductions_cache
    return _reductions_cache


def _missing_data_fig(msg):
    fig, ax = plt.subplots()
    ax.text(0.5, 0.5, msg, ha='center', va='center', transform=ax.transAxes)
    ax.axis('off')
    return fig


def chart_zipllm_real_cdf(rc):
    """Per-tensor space saving CDF for all methods."""
    for path in [_ZIPLLM_CSV, _METADATA_DB, _CACHE_JSON]:
        if not os.path.exists(path):
            return _missing_data_fig(
                f"Data not found:\n{path}\n\nRun plots/model_level_reduction/zipllm_real_simulation.py first.")

    all_savings = _sim_load_savings()

    fig, ax = plt.subplots(figsize=(rc["figsize_w"], rc["figsize_h"]))

    for label, data in all_savings.items():
        if len(data) == 0:
            continue
        color, ls, lw = _METHOD_STYLES.get(label, ("#333", "-", 2.0))
        sorted_data = np.sort(data)
        cdf = np.linspace(0, 1, len(sorted_data))
        step = max(1, len(sorted_data) // 5000)
        display_label = _BAR_LABELS_MAP.get(label, label.replace("\n", " "))
        ax.plot(sorted_data[::step], cdf[::step],
                label=display_label, color=color, linestyle=ls, linewidth=lw)

    ax.set_xlabel("Tensor Reduction Ratio (%)")
    ax.set_ylabel("Cumulative Probability")
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 1.02)
    ax.legend(loc="upper left", frameon=True, fontsize=rc["legend_size"],
              handlelength=1.0, handletextpad=0.4)
    ax.grid(True, alpha=rc["grid_alpha"], color=rc["grid_color"],
            linewidth=rc["grid_linewidth"])
    fig.tight_layout()
    return fig


def chart_zipllm_real_bar(rc):
    """Normalized storage reduction bar chart (Full = 1.0x baseline)."""
    for path in [_ZIPLLM_CSV, _METADATA_DB, _CACHE_JSON]:
        if not os.path.exists(path):
            return _missing_data_fig(
                f"Data not found:\n{path}\n\nRun plots/model_level_reduction/zipllm_real_simulation.py first.")

    reductions = _sim_load_reductions()

    first_key = list(reductions.keys())[0]
    orig_gb = reductions[first_key]["orig_gb"]

    # Explicit bar order: Full, OpenZL, ZipNN, FM-Delta, ZipLLM, TensorDex-TX, TensorDex-FM
    _bar_order = ["OpenZL", "ZipNN", "ZipLLM", "ZipLLM-Oracle", "TensorDex-TX", "TensorDex-FM"]
    ordered_keys = [k for k in _bar_order if k in reductions]

    all_labels  = ['Full']
    all_heights = [1.0]
    all_colors  = [_FULL_GRAY]

    for key in ordered_keys:
        display = _BAR_LABELS_MAP.get(key, key)
        norm = reductions[key]["stored_gb"] / orig_gb  # normalized to Full
        all_labels.append(display)
        all_heights.append(norm)
        color, _, _ = _METHOD_STYLES.get(key, (_FULL_GRAY, "-", 8))
        all_colors.append(color)

    fig, ax = plt.subplots(figsize=(rc["figsize_w"], rc["figsize_h"]))

    x = range(len(all_labels))
    bars = ax.bar(x, all_heights, color=all_colors, edgecolor='white',
                  linewidth=0.5, width=0.7)

    ann_sz = 42
    for bar, h, label in zip(bars, all_heights, all_labels):
        cx = bar.get_x() + bar.get_width() / 2
        ax.text(cx, 0.05, f'{h:.2f}x',
                ha='center', va='bottom', rotation=90,
                fontsize=ann_sz, color='black',
                fontweight='bold' if label == 'Full' else 'normal')

    ax.set_xticks([])
    ax.set_ylabel('Normalized Storage (x)')
    ax.set_ylim(0, 1.18)
    ax.axhline(1.0, color='#aaaaaa', linestyle='--', linewidth=1.5, alpha=0.6, zorder=1)
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f'{v:.2f}x'))

    # Legend
    from matplotlib.patches import Patch
    legend_handles = [Patch(facecolor=_FULL_GRAY, edgecolor='white', label='Full')]
    for key in ordered_keys:
        color, _, _ = _METHOD_STYLES.get(key, (_FULL_GRAY, "-", 8))
        lbl = _BAR_LABELS_MAP.get(key, key.replace("\n", " "))
        legend_handles.append(Patch(facecolor=color, edgecolor='white', label=lbl))
    ax.legend(handles=legend_handles, loc="upper right", ncol=2,
              fontsize=rc["legend_size"], handlelength=1.0, handletextpad=0.4,
              columnspacing=0.5)

    fig.tight_layout()
    return fig


def _per_model_reduction(df_trace):
    """Compute per-model reduction % from a cumulative trace DataFrame."""
    cum_orig = df_trace["cum_original_bytes"].values.astype(float)
    cum_stor = df_trace["cum_stored_bytes"].values.astype(float)
    per_orig = np.diff(cum_orig, prepend=0)
    per_stor = np.diff(cum_stor, prepend=0)
    result = df_trace[["family"]].copy()
    result["reduction"] = np.where(per_orig > 0, (1.0 - per_stor / per_orig) * 100.0, np.nan)
    result = result.dropna(subset=["reduction"])
    return result[result["family"].str.lower() != "other"]


def chart_reduction_violin_by_family(rc):
    """Side-by-side violin plot: TensorDex-TX vs TensorDex-FM vs ZipLLM per-model reduction."""
    df_fs, df_zp = _load_trace_csvs()
    if df_fs is None:
        return _missing_data_fig("Data not found.\nRun plots/model_level_reduction/plot.py first.")

    # TensorDex-TX per-model reduction
    red_tx = _per_model_reduction(df_fs)

    # ZipLLM (was ZipLLM-Oracle) per-model reduction
    red_zp = _per_model_reduction(df_zp) if df_zp is not None and not df_zp.empty else None

    # TensorDex-FM per-model reduction (from FM-Delta trace)
    _fm_traces = _build_fm_traces(df_fs)
    tdx_fm_trace = _fm_traces.get("flexsplit")
    red_fm = None
    if tdx_fm_trace is not None:
        cum_orig = df_fs["cum_original_bytes"].values.astype(float)
        per_orig = np.diff(cum_orig, prepend=0)
        # Derive per-model stored from cumulative reduction trace
        cum_fm_stored = cum_orig * (1.0 - tdx_fm_trace / 100.0)
        per_fm_stored = np.diff(cum_fm_stored, prepend=0)
        fm_red = np.where(per_orig > 0, (1.0 - per_fm_stored / per_orig) * 100.0, np.nan)
        red_fm = df_fs[["family"]].copy()
        red_fm["reduction"] = fm_red
        red_fm = red_fm.dropna(subset=["reduction"])
        red_fm = red_fm[red_fm["family"].str.lower() != "other"]

    # Fixed family order: similar models grouped together
    _FAMILY_ORDER = [
        "Qwen/Qwen2.5-7B", "Qwen/Qwen3-8B",
        "mistralai/Mistral-7B-v0.1", "mistralai/Mistral-7B-Instruct-v0.3",
        "google/gemma-2-9b-it", "google/gemma-3-4b-it",
        "meta-llama/Meta-Llama-3-8B", "meta-llama/Llama-3.1-8B",
        "meta-llama/Llama-3.1-8B-Instruct", "meta-llama/Llama-3.2-3B",
    ]
    available = set(red_tx["family"].unique())
    family_order = [f for f in _FAMILY_ORDER if f in available]
    # Append any remaining families not in the fixed order
    for f in sorted(available):
        if f not in family_order and f.lower() != "other":
            family_order.append(f)

    # Short labels for x-axis
    _FAMILY_LABELS = {
        "Qwen/Qwen2.5-7B":                       "Qwen2.5",
        "Qwen/Qwen3-8B":                          "Qwen3",
        "mistralai/Mistral-7B-v0.1":              "Mistral-v0.1",
        "mistralai/Mistral-7B-Instruct-v0.3":     "Mistral-v0.3",
        "meta-llama/Meta-Llama-3-8B":             "Llama-3",
        "meta-llama/Llama-3.1-8B":                "Llama-3.1",
        "meta-llama/Llama-3.1-8B-Instruct":       "Llama-3.1-Inst",
        "meta-llama/Llama-3.2-3B":                "Llama-3.2",
        "google/gemma-2-9b-it":                   "Gemma-2",
        "google/gemma-3-4b-it":                   "Gemma-3",
    }
    def _shorten(f):
        return _FAMILY_LABELS.get(f, f.split("/")[-1] if "/" in f else f)
    short_labels = [_shorten(f) for f in family_order]

    data_tx = [red_tx.loc[red_tx["family"] == f, "reduction"].values for f in family_order]
    data_fm = [red_fm.loc[red_fm["family"] == f, "reduction"].values for f in family_order] if red_fm is not None else None
    data_zp = [red_zp.loc[red_zp["family"] == f, "reduction"].values for f in family_order] if red_zp is not None else None

    fig, ax = plt.subplots(figsize=(rc["figsize_w"], rc["figsize_h"]))

    n = len(family_order)
    positions = np.arange(n)
    width = 0.28

    color_tx = "#b3de69"                  # TensorDex-TX (swapped)
    color_fm = COLORS_LOCAL["flexsplit"]   # TensorDex-FM (swapped)
    color_zp = COLORS_LOCAL["zipllm"]      # ZipLLM (was ZipLLM-Oracle)

    def _draw_violin(ax, data, pos, color, med_color):
        parts = ax.violinplot(data, positions=pos,
                              widths=width * 0.9, showmedians=False, showextrema=False)
        for body in parts["bodies"]:
            body.set_facecolor(color)
            body.set_edgecolor("black")
            body.set_linewidth(0.6)
            body.set_alpha(0.7)
        bp = ax.boxplot(data, positions=pos, widths=width * 0.2,
                        patch_artist=True, showfliers=False, zorder=3)
        for patch in bp["boxes"]:
            patch.set_facecolor("white")
            patch.set_edgecolor("black")
            patch.set_linewidth(0.8)
        for el in ["whiskers", "caps"]:
            for line in bp[el]:
                line.set_color("black")
                line.set_linewidth(0.8)
        for line in bp["medians"]:
            line.set_color(med_color)
            line.set_linewidth(1.8)

    # ── TensorDex-FM violins (left) ──
    if data_fm is not None:
        _draw_violin(ax, data_fm, positions - width, color_fm, color_fm)
    # ── TensorDex-TX violins (center) ──
    _draw_violin(ax, data_tx, positions, color_tx, color_tx)
    # ── ZipLLM violins (right) ──
    if data_zp is not None:
        _draw_violin(ax, data_zp, positions + width, color_zp, color_zp)

    # X-axis: short family names
    ax.set_xticks(positions)
    ax.set_xticklabels(short_labels, fontsize=rc["tick_label_size"] * 0.7, rotation=15, ha="center")
    ax.tick_params(axis="y", labelsize=rc["tick_label_size"])
    ax.set_ylabel("Per-Model Reduction %", fontsize=rc.get("label_size", 42))
    ax.set_xlabel("Model Family", fontsize=rc.get("label_size", 42))
    ax.set_ylim(bottom=-5)
    ax.yaxis.set_major_locator(mticker.MaxNLocator(nbins=5))
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.0f%%"))

    # Method legend
    from matplotlib.patches import Patch
    legend_items = [
        Patch(facecolor=color_fm, edgecolor="black", label="TensorDex-FM"),
        Patch(facecolor=color_tx, edgecolor="black", label="TensorDex-TX"),
        Patch(facecolor=color_zp, edgecolor="black", label="ZipLLM"),
    ]
    ax.legend(handles=legend_items, loc="lower right",
              fontsize=rc["legend_size"], frameon=True,
              handlelength=1.0, handletextpad=0.4)

    plt.tight_layout()
    return fig


CHARTS = {
    "reduction_global": {
        "name": "Global Storage Reduction",
        "category": "Model-Level",
        "desc": "Cumulative reduction % with family scatter",
        "fn": chart_reduction_global,
    },
    "reduction_by_family": {
        "name": "Storage Reduction by Family",
        "category": "Model-Level",
        "desc": "Normalized storage cost per model family",
        "fn": chart_reduction_by_family,
    },
    "reduction_trace": {
        "name": "Reduction Comparison Trace",
        "category": "Model-Level",
        "desc": "3-panel reduction, storage, and tensor breakdown",
        "fn": chart_reduction_comparison_trace,
    },
    "zipllm_real_cdf": {
        "name": "Storage Reduction CDF",
        "category": "Model-Level",
        "desc": "Per-tensor space saving CDF for all methods",
        "fn": chart_zipllm_real_cdf,
    },
    "zipllm_real_bar": {
        "name": "Storage Reduction Bar",
        "category": "Model-Level",
        "desc": "Overall storage reduction bar chart for all methods",
        "fn": chart_zipllm_real_bar,
    },
    "reduction_violin_by_family": {
        "name": "Reduction Distribution by Family",
        "category": "Model-Level",
        "desc": "Violin plot of per-model reduction % grouped by model family",
        "fn": chart_reduction_violin_by_family,
    },
}
